### ISSUE TITLE
[회원가입] TODO 및 이슈

### ISSUE THREAD

**Issue by choheeis** [Capstone-FoodDeuk/Fooddeuk-Android#39]
- [ ] 회원가입 세부 기능 아직 구현 안 됨
  - 아이디, 비번 글자수 제한이나 중복 확인, 비밀번호 확인 체크 등등
- [ ] 이용 약관 쪽
- [ ] 키보드 위로 노출될 때 뷰가 status bar 위로 올라가서 깨져보임
- [ ] 키보드로 인해 가려지는 뷰가 생기면 위로 자동으로 스크롤? 됐으면 좋겠음 ⠀
